### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by skibz** [sindresorhus/uint8array-extras#1]
One of the most useful bits of functionality offered by `Buffer` is how it makes it trivial to convert data between several encodings.

A plain `TypedArray` is woefully deficient in this area, and the equivalent constructs one is required to implement are about as enjoyable as rubbing onions in your eyes.

Any plans to support this for libraries or applications that depend on `Buffer` for this reason?

**Comment by sindresorhus** [comment]
By "encodings", I assume you mean string encodings? What specific encodings do you use?

**Comment by skibz** [comment]
[Here's](https://nodejs.org/dist/latest-v20.x/docs/api/buffer.html#buffers-and-character-encodings) the run-down.

**Comment by sindresorhus** [comment]
I'm aware of what `Buffer` is capable of, but I'm more curious what you use specifically. I cannot support all encodings, but I could try to support the most popular usages.

**Comment by skibz** [comment]
Understood.

The majority of the code I'm maintaining uses `base64`, `hex`, and `utf16le`.

**Comment by sindresorhus** [comment]
I added Base64 support in the latest update. I will look into Hex support.

It also seems like Base64 support will eventually come natively: https://github.com/tc39/proposal-arraybuffer-base64

**Comment by skibz** [comment]
Gravy :+1:

**Comment by sindresorhus** [comment]
It now also supports Hex.

**Comment by mattbishop** [comment]
I would also like to see `base64url` support:

```js
Buffer.from(param, "base64url")
```

**Comment by sindresorhus** [comment]
@mattbishop Added in the latest update: https://github.com/sindresorhus/uint8array-extras/releases/tag/v0.4.0

**Comment by mattbishop** [comment]
Thanks @sindresorhus !

**Comment by sindresorhus** [comment]
I'm going to leave out `utf16le` for now as it's not something I need personally, but I'm happy to add it if someone wants to do the work.
