### ISSUE TITLE
Performances implications of switching from Buffer to Uint8Array

### ISSUE THREAD

**Issue by robertsLando** [sindresorhus/uint8array-extras#2]
I would be curious to know what are the performances implications about this, will the transition boost or reduce performances? Browser apart where Buffer is polifilled using Uint8Array, Uint8Array could be drammatically slower in nodejs environments compared to Buffer

**Comment by sindresorhus** [comment]
Performance should in theory be the same for most operations as `Buffer` is a subclass of `Uint8Array`.

`Buffer` does have some unique performance optimizations with pooling, but that also [has problems](https://github.com/nodejs/node/issues/41588#issuecomment-1016952897).

The main potential performance problems are encoding/decoding to Base64/Hex as `Uint8Array` doesn't have any native handling for that, [yet](https://github.com/tc39/proposal-arraybuffer-base64). But it really depends on your usage and how performance sensitive your code is. The Hex conversion methods in this package should be pretty fast though.

**Comment by robertsLando** [comment]
Thanks for the links provided, I think that creating a banchmark test would be useful to make clear the benefits and the downsides of the move (right now).

**Comment by jimmywarting** [comment]
if you want some better / faster perf, have a look at: https://github.com/ThaUnknown/uint8-util
i helped out increasing webtorrent speed with this and also the buffer browserified version of eg to/from hex

**Comment by sindresorhus** [comment]
> if you want some better / faster perf, have a look at: https://github.com/ThaUnknown/uint8-util

This is not a useful comment. At minimum explain how it's faster. Ideally, back it up with benchmarks.

**Comment by navalny-fbk** [comment]
> At minimum explain how it's faster. Ideally, back it up with benchmarks

i explained how other libs are faster and even backed up with benchmarks. 
however you just decided that my issue is not good enough, deleted it and banned me.

i checked your contribution guidelines and it has ZERO mentions that i can't be toxic when it's relevant. so yeah. good luck with being an asshole
