### ISSUE TITLE
Buffer to Uint8Array conversion method?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/uint8array-extras#4]
`Buffer` is a subclass of `Uint8Array`, so you can generally treat it like a `Uint8Array`. However, [`Buffer` changes the behavior of the `.slice()` method](https://sindresorhus.com/blog/goodbye-nodejs-buffer), so treating it like a `Uint8Array` may cause subtle problems.

Converting to `Uint8Array` can be done as follows:

Copy:

```js
new Uint8Array(buffer);
```

Cast (non-copy):

```js
new Uint8Array(buffer.buffer, buffer.byteOffset, buffer.byteLength);
```

Casting is probably what you would want to do most of the time, so it could maybe make sense to have a method for it here as it's quite verbose. And also for documentation purposes.

Thoughts?

**Comment by jimmywarting** [comment]
> Casting is probably what you would want to do most of the time

yes.


You can steal my [to-uint8array](https://www.npmjs.com/package/to-uint8array) and inline it if u like.

- it downgrades everything that extends uint8array into a normal uint8array (without copy) and all other typed ArrayBufferViews (incl. DataView)
- anything that isn't a ArrayBuffer or a ArrayBufferView is casted to a string and then converted to uint8array using the textEncoder.encode. This would match things such as how Blob constructor, fetch and other things normalize strings into byte arrays. and also look similar to `Buffer.from('string')`

```js
var textEncoder = new TextEncoder();

/**
 * Convert anything to Uint8Array without a copy
 */
export default function uint8From(x) {
  if (x instanceof ArrayBuffer) {
    return new Uint8Array(x);
  } else if (ArrayBuffer.isView(x)) {
    if (x instanceof Uint8Array && x.constructor.name === Uint8Array.name) {
      return x;
    } else {
      return new Uint8Array(x.buffer, x.byteOffset, x.byteLength);
    }
  } else {
    return textEncoder.encode(x);
  }
}
```

this way you can also support stuff like custom toString and Symbol.toPrimitive

thinking about it even more... you could do stuff like: `uint8From(string, 'base64')`
then you may not need `stringToUint8Array`, or `base64ToUint8Array` and would be a closer match to `Buffer.from(string, 'base64')`

**Comment by sindresorhus** [comment]
My thinking was to accept anything that's `x instanceof Uint8Array`, but I guess I can include any typed array and ArrayBuffer for convenience.

---

> anything that isn't a ArrayBuffer or a ArrayBufferView is casted to a string and then converted to uint8array using the textEncoder.encode.

I would not want such a magic behavior.

> thinking about it even more... you could do stuff like: uint8From(string, 'base64')
then you may not need stringToUint8Array, or base64ToUint8Array and would be a closer match to Buffer.from(string, 'base64')

Matching `Buffer` is a non-goal. It's not a very good API.
