### ISSUE TITLE
loader fail with  Unexpected token

### ISSUE THREAD

**Issue by ixqbar** [sindresorhus/uint8array-extras#6]
./node_modules/.pnpm/uint8array-extras@0.5.0/node_modules/uint8array-extras/index.js 34:15
Module parse failed: Unexpected token (34:15)
File was processed with these loaders:
 * ./node_modules/.pnpm/babel-loader@8.0.6_@babel+core@7.7.4_webpack@4.41.2/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   }
|
>   totalLength ??= arrays.reduce((accumulator, currentValue) => accumulator + currentValue.length, 0);
|   const returnValue = new Uint8Array(totalLength);
|   let offset = 0;

**Comment by sindresorhus** [comment]
This is a problem with your bundler, not this package.
